/**
 * Created by dman on 27/09/2017.
 */
'use strict'
module.exports = Object.freeze({
  UNKNOWN: 'UNKNOWN',
  CREATE: 'CREATE',
  READ: 'READ',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  APP_START: 'APP_START',
  APP_STOP: 'APP_STOP',
  UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
  SERVICE_START: 'SERVICE_START',
  SERVICE_STOP: 'SERVICE_STOP',
  RESPONSE_SENT: 'RESPONSE_SENT',
  REQUEST_RECEIVED: 'REQUEST_RECEIVED'
})
